const STATUS_CODE = {
  SUCCESSFUL_RESPONSE_CODE: 200,
  SUCCESSFULLY_CREATED_RESPONSE_CODE: 201,
  CLIENT_ERROR_RESPONSE_CODE: 400,
  SERVER_ERROR_RESPONSE_CODE: 500,
};

module.exports = { STATUS_CODE };
